# History
#defaults:
#  - override hydra_logging: colorlog
#  - override job_logging: colorlog
#
#job:
#  chdir: True
#
## output directory, generated dynamically on each run
#run:
#  dir: ${pipelines.pipeline.task_dir_path}/hydra/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
#sweep:
#  dir: ${pipelines.pipeline.task_dir_path}/hydra/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
#  subdir: ${hydra.job.num}


# New
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
job:
  chdir: null
output_subdir: null
run:
  dir: .

